rexray:
  loglevel: warn
libstorage:
  service: ebs
  integration:
    volume:
      operations:
        create:
          default:
            fsType: ext4
        mount:
          preempt: false
  server:
    services:
      ebs:
        driver: ebs
